### ISSUE TITLE
iOS Voiceover - empty input says '1 result available'

### ISSUE THREAD

**Issue by adamliptrot-oc** [alphagov/accessible-autocomplete#200]
When arriving at the autocomplete for the first time and moving from the label to the input, Voiceover announces '1 result available'.
The next navigable item is 'comma' which looks to be a comma inside a span tag.

![image](https://user-images.githubusercontent.com/14074579/28427120-146548e8-6d6d-11e7-9dd5-8b9784fbc94e.png)
(screenshots from Chrome to show code issue)

Not sure what the purpose of the comma is? Also looks that as you interact with the autocomplete, the comma is doubled.

![image](https://user-images.githubusercontent.com/14074579/28427251-7a0cb172-6d6d-11e7-80bb-3ac60b81c416.png)

The erroneous result count and presence of the comma is confusing for the user.

**Comment by tvararu** [comment]
The 1 result is available sounds like a bug. It should say "No search results."

---

The comma is a hack. 😄 

Let's say you've typed in `unit` and have the following results:

- United States
- United Arab Emirates
- United Kingdom

The first time you finish typing `unit` you'll hear "3 results are available."

When you key in `e` and you change to `unite`, the number of results doesn't change. The `aria-status` region remains unchanged, users don't hear any feedback, so users think the autocomplete isn't searching anymore.

The way this was [previously solved](https://github.com/alphagov/accessible-autocomplete/pull/13) is by using a debounced `setTimeout` to clear the content of the aria status region. This is an approach used by other autocompletes, but I've found it to be buggy.

The comma hack by contrast (combined with `aria-atomic`) works, but may confuse the user. For what it's worth, only VoiceOver consistently pronounces it! NVDA or JAWS I found would sometimes simply ignore it.

While this particular quirk has not been user tested with screen reader users, from speaking with other accessibility developers the consensus was that it shouldn't be a barrier. SR users are used to hearing all kinds of weird stuff from their screen readers, whether it's mispronounced dates, "Governor UK," or punctuation in odd places. It's far more important to consistently report the count of results.

That being said, if you can think of a better way to fix the underlying issue, by all means we should use that instead. 👍

**Comment by adamliptrot-oc** [comment]
The second comma seemed to appear when you interact with the autocomplete, but when trying to replicate it, it looks like it's always there.

**Comment by tvararu** [comment]
@adamliptrot-oc cool, then yes that's a legitimate bug and we should look at it.

**Comment by tvararu** [comment]
For the comma hack I suggest we move discussion to https://github.com/alphagov/accessible-autocomplete/issues/207

**Comment by hannalaakso** [comment]
Hi Adam,

Thanks for flagging this up and apologies for taking so long to reply.

We haven't been able to replicate iOS reading out the wrong number of results. We've tested the [demo page](https://alphagov.github.io/accessible-autocomplete/examples/) on these devices/browsers:

- iPad 10.3.3 - Safari 
- iPad i11.3.1 - Safari
- iPhone 11.2.1 - Safari and Chrome

Steps:
1. When I enter the field, VoiceOver says: "Select your country. Text field. Double tap to edit." 
2. After typing in "a", I hear "220 results are available".  When I type in "f" so that the input value is "af", I hear "3 results are available". 

Do you know what version of iOS you saw the bug on? Are you able to replicate it on the [demo page](https://alphagov.github.io/accessible-autocomplete/examples/)?

Thanks,
Hanna

**Comment by hannalaakso** [comment]
Hi Adam,

As mentioned we haven't been able to reproduce this issue. I am closing this for now but please re-open if you think this is still an issue.

Thanks,
Hanna
