### ISSUE TITLE
Progressively-enhanced select tries to filter by defaultValue

### ISSUE THREAD

**Issue by alecgibson** [alphagov/accessible-autocomplete#221]
## Screenshot

<img width="207" alt="screen shot 2017-08-25 at 11 48 34" src="https://user-images.githubusercontent.com/12036746/29711126-5ffa386a-898b-11e7-8d19-8549b992cd50.png">

## Reproduction steps

1. Set up a progressively-enhanced `select` with a `null` option and a `defaultValue` (eg `defaultValue: 'Select...'`)
1. Click the dropdown arrow
1. Notice that no results are found
1. Clear the `defaultValue` text ("Select...") from the autocomplete box
1. Notice that results are now visible

## What I expect to happen

When I have a `null` option with a `defaultValue`, I would expect clicking on the dropdown to do one of:

- Clear the `input` field
- Disregard the `defaultValue` when filtering options

**Comment by alecgibson** [comment]
This may be closely related to: https://github.com/alphagov/accessible-autocomplete/issues/205

**Comment by dracos** [comment]
It sounds like what you want to do is have `defaultValue: ""` and `placeholder: "Select..."`.
`defaultValue` is a value, not a display element.

**Comment by alecgibson** [comment]
There's a related issue to this, which is:

## Screenshot

<img width="264" alt="screen shot 2017-09-25 at 11 30 11" src="https://user-images.githubusercontent.com/12036746/30804327-f1a73076-a1e4-11e7-8816-de256af17114.png">

## Reproduction steps

1. Set up a progressively-enhanced `select` element
2. Select an item
3. Click on the dropdown arrow
4. I can only see the item I have already selected

## What I expect to happen

When I'm clicking on the dropdown arrow, expect to see all the available options (as if the box was clear), instead of just being able to choose the option I've already chosen.

**Comment by dracos** [comment]
Unless I'm misunderstanding something, that is not related to this issue (it has nothing to do with `defaultValue`). I was just pointing out I don't think this issue is an issue.

**Comment by alecgibson** [comment]
> it has nothing to do with `defaultValue`

Not according to [the docs][docs]:
> Default the autocomplete `defaultValue` to the select's `option[selected]`

[docs]: https://github.com/alphagov/accessible-autocomplete#progressive-enhancement

**Comment by edwardhorsford** [comment]
@alecgibson could you raise that as a separate issue?

**Comment by alecgibson** [comment]
Raised here: https://github.com/alphagov/accessible-autocomplete/issues/240
Feel free to close this if you think this in particular is not an issue.

**Comment by hannalaakso** [comment]
Hi @alecgibson 

Thanks for raising this. Apologies for the long delay in replying to this.

As @dracos commented, it sounds like you might need to use `defaultValue: ""` and `placeholder: "Select..."`

From the screenshot you posted it looks like you're using the `showAllValues: true` version: unfortunately there's a [bug with the placeholder](https://github.com/alphagov/accessible-autocomplete/issues/259) in it that I just raised. So the solution for now would be to use the standard select.

Note also that placeholders are [generally not recommended](https://github.com/alphagov/accessible-autocomplete#placeholder-default--warning-not-recommended-warning) - a better solution might be to include any essential information in the label of the input and not to have a placeholder at all.

I'm closing this ticket as I think this is not an issue but please re-open it if you think otherwise.

Cheers,
Hanna
