### ISSUE TITLE
Progressively enhanced select with show all values will select first option on blur

### ISSUE THREAD

**Issue by alecgibson** [alphagov/accessible-autocomplete#236]
## Screenshot

![autocomplete-autoselect](https://user-images.githubusercontent.com/12036746/30375543-cf7a3506-9880-11e7-8be2-7cf22cc248c4.gif)

## Reproduction steps

1. Set up a `select` element whose first `option` is blank (eg `<option value=""></option>`)
1. Set up a progressively enhanced autocomplete, with `showAllValues: true` and `autoselect: true`
1. Click on the autocomplete
1. Click outside the autocomplete
1. The first option has been selected

## What I expect to happen

When blurring an autocomplete with no text entered, I expect no option to be selected, even if `autoselect` is enabled.

**Comment by edwardhorsford** [comment]
Thanks @alecgibson for the bug report. I agree with your expectations.

I think an item should only get selected once a user types x or more characters.

**Comment by hannalaakso** [comment]
Hi @alecgibson

Thanks for raising this. Apologies for the long delay in replying.

For now, you can fix this by setting `preserveNullOptions: true`. However I think this should be the default behaviour. 

I am closing this issue as the implications of the wider issue here are captured in https://github.com/alphagov/accessible-autocomplete/issues/260. However please re-open issue if you think otherwise.

Cheers,
Hanna
