### ISSUE TITLE
Functionality: Down key show all results?

### ISSUE THREAD

**Issue by nickcolley** [alphagov/accessible-autocomplete#31]
Not sure if this is a good idea, but when I use keyboard input on a select input, then press down on the keyboard, it'll open the select and let me go through them.

**Comment by tvararu** [comment]
I don't see why we shouldn't do this, @edwardhorsford what do you think?

**Comment by nickcolley** [comment]
This could cause performance issues if the list is very long though...

**Comment by tvararu** [comment]
@nickcolley there's situations in which you can't do it like if you rely on async results (which are not built yet), or indeed if the total list of results is too large. If the list is something like the days of the week, "Monday" to "Sunday", I think it could be good to have a way to bring up the list even before the user types anything.

**Comment by edwardhorsford** [comment]
I have no immediate objection to the idea, but with the current styling don't expect any users to actually do this.

If we try it I'd want to make sure selection works as expected.

**Comment by nickcolley** [comment]
> If we try it I'd want to make sure selection works as expected.

What do you mean by 'selection'?

**Comment by adamsilver** [comment]
I think we should be able to configure the typeahead to show the options within it, like a native select. To make that clear to the user, I think we should have a down arrow (or similar). Clicking it, as well as pressing the DOWN key, should those options.

**Comment by tvararu** [comment]
Right, this is a good feature, and we should provide an option.

Off the top of my head these two things need to be updated to enable this:

- The typeahead would need the ability to call the `source` function even when the query is empty, which is currently a [hardcoded constraint](https://github.com/alphagov/accessible-typeahead/blob/784d74fae7473e0c2eed8e02f27ea6ef21750fa6/src/typeahead.jsx#L177)
- The [down arrow handler](https://github.com/alphagov/accessible-typeahead/blob/784d74fae7473e0c2eed8e02f27ea6ef21750fa6/src/typeahead.jsx#L265) needs to open the menu if it's collapsed and there are available options

The tests will need to be updated to reflect the new behaviours too, and it will also need an example (like picking from Monday to Sunday).

I'm currently prioritising productisation features, but if anyone else wants to pick it up I'm happy to provide further guidance.

**Comment by edwardhorsford** [comment]
@adamsilver Could you describe an example use case?

I think it's something that may be useful, but would be good to work on the design and test in user research - I have the feeling that it could introduce some usability issues.

**Comment by adamsilver** [comment]
Hi @edwardhorsford . The behaviour I am talking about is basicaly the HTML5 datalist but not a buggy version.

[Here's an example](https://developer.mozilla.org/en/docs/Web/HTML/Element/datalist#result)

On UC we have something like this. Here's a [screenshot](https://drive.google.com/open?id=0B8GCIok3ZxJZNnZBX1AxQm5LYVVtX3ZwMTFESmRPM2Y0dmdF).

It looks similar to a native select until the user interacts with it. As they do focus is moved to a textbox with a search capability. If the user wants to scroll the options (instead of typing) then they can do so, just like a native select.

In several observations, some users have used the search functionality and some prefer to just scroll the long list anyway.

What usability issues do you feel it could introduce?

**Comment by edwardhorsford** [comment]
Hi Adam,

This is similar to this design I sketched a few weeks ago (untested):
![screen shot 2017-04-10 at 15 04 04](https://cloud.githubusercontent.com/assets/2204224/24865609/ad6b1aee-1dff-11e7-8aa0-cab1adbeea70.png)

I think there's two things here: showing the menu when pressing down arrow, and showing the menu when focusing the field (or clicking the button as in my example and your screenshot). Both are things I think it would be good to try, but I'd like to do usability testing to see how users interact with them.

I'd still like to try a variation of the designs above, but we have been focusing on the basic usability and accessibility _first_.

For showing the menu on down arrow press: I don't see much risk in supporting it, but haven't observed any users attempt it. Without more affordance, it's unlikely users will attempt it. I wouldn't want to add more affordance without doing usability testing to see how users interact with it. @tvararu any thoughts on supporting this? Is it an easy one for me to try?

**Comment by tvararu** [comment]
@edwardhorsford I think adding support for the down arrow feature is low risk and easy to support. I quickly brushed over the parts that need to change in [my comment above](https://github.com/alphagov/accessible-typeahead/issues/31#issuecomment-292118618). I think the feature is easy to build and a good intro into the event handling guts of the typeahead.

Happy to provide further guidance to you or anyone else who wants to pick up this work, which is why I've market it as "good for beginners." :1st_place_medal:

**Comment by adamsilver** [comment]
Hi Ed, thanks for explaining that to me.

Is your concern with the arrow, one that is related to usability concerns or is it that you don't want to add *more* until user testing shows that *more* is needed? Or something else?

**Comment by edwardhorsford** [comment]
@adamsilver something between all of them. 

Usability testing so far has shown the country picker is working really well. I'd like to try such a feature, but would want to do usability testing of it before releasing it. 

Off hand, I'd want to make sure that it's not overwhelming if it exposes hundreds of results, and it doesn't impact on accessibility.

If you'd like to create a branch to play with, we can explore it there?

**Comment by adamsilver** [comment]
Here you go @edwardhorsford.

[Autocomplete Demo](http://adamsilver.github.io/kitty/src/demos/Autocomplete/)

Tried to match the GDS one as close as possible.

**Comment by nickcolley** [comment]
Since this a request from me, a power user of the web and not the core demographic for this component I'm going to close this but we can re-open this if we find users need this behaviour in the future.

Thanks everyone for helping thinking this through.
