### ISSUE TITLE
Autocomplete uses fixed ids which could cause issues with multiple autocompletes on a page.

### ISSUE THREAD

**Issue by spacedmonkey** [alphagov/accessible-autocomplete#378]
The element `assistiveHint` has two issues. 

1. Why does it have a fixed id? Does means you can't have autocompletes in one page. 
2. Why is `display: 'none'` used here? Should it use something like this 
```
/* Text meant only for screen readers. */
.screen-reader-text {
  border: 0;
  clip: rect(1px, 1px, 1px, 1px);
  clip-path: inset(50%);
  height: 1px;
  margin: -1px;
  overflow: hidden;
  padding: 0;
  position: absolute;
  width: 1px;
  word-wrap: normal !important;
}
```
[Props](https://make.wordpress.org/accessibility/handbook/markup/the-css-class-screen-reader-text/#the-css) WordPress.org.

**Comment by nickcolley** [comment]
Hey @spacedmonkey ,

1. That's a very good point, while the most common use case we'd only expect one autocomplete on  a page there's certainly people that need to do this. We should investigate making sure this id is unique.

2. We can use `display: none` here without issue since this text is read about by the association with `aria-describedby`.

I'll update this issue to reflect the issue with the id, thanks for helping out.
