### ISSUE TITLE
Autocomplete with pre selected value showing undefined

### ISSUE THREAD

**Issue by jonheslop** [alphagov/accessible-autocomplete#383]
Hello,

We're seeing this error when we upgrade to the latest accessible-autocomplete

![autocomplete-error](https://user-images.githubusercontent.com/440503/66474859-0d3d0500-ea8a-11e9-9a9f-c7ab240156c0.gif)

The undefined is coming from here I think
https://github.com/alphagov/accessible-autocomplete/pull/355/files#diff-42909ce1eee782a4254962bd5bfe2a04R103

It probably makes things more complex but we're actually using https://github.com/alphagov/govuk-country-and-territory-autocomplete/

We're using the progressive enhancement version

```
  <script type="text/javascript" src="/public/location-autocomplete.min.js"></script>
  <script type="text/javascript">
    openregisterLocationPicker({
      selectElement: document.getElementById('address-country'),
      url: '/public/countries-autocomplete-graph.json',
      autoselect: true,
      displayMenu: 'overlay'
    })
  </script>
```

https://github.com/alphagov/pay-frontend/blob/master/app/views/charge.njk#L502-L509

**Comment by jonheslop** [comment]
Can replicate by adding https://github.com/alphagov/govuk-country-and-territory-autocomplete/commit/34acd15dfc5cee49bd4a345a957af72ead6992e4#diff-5b0e3367cfabe5a0173e80753b827d6cR615

**Comment by jonheslop** [comment]
Was a downstream problem with the `suggestionTemplate` that the alphagov/govuk-country-and-territory-autocomplete used 

Have fixed here - https://github.com/alphagov/govuk-country-and-territory-autocomplete/pull/66

**Comment by nickcolley** [comment]
Thanks a lot for fixing this, I wonder if we made an unintentional breaking change for this to happen, should we investigate why you need to make this update upstream?

**Comment by nickcolley** [comment]
I've had a look into some of this:

When you revert the accessible-autocomplete to 1.0.0 you can see in the source code there is an 'undefined' item but it is not shown

There is new behaviour in 2.x that looks at the query typed against the options to see if they match, if they do not match it will show the options. This is why the 'undefined' option pops up.

So I think we should investigate why the options were being displayed as undefined until the user adds a query.

I think... it's because the defaultValue is a string:
https://github.com/alphagov/accessible-autocomplete/blob/master/src/wrapper.js#L34

Whereas the query engine for the country picker uses objects.

**Comment by nickcolley** [comment]
So my conclusion is that the country picker has always had a default options list of 'undefined', and that is the problem, so we should fix it downstream in that repository?
