### ISSUE TITLE
aria-controls instead of aria-owns?

### ISSUE THREAD

**Issue by jeremyZX** [alphagov/accessible-autocomplete#565]
In reviewing the [WAI ARIA combobox pattern](https://www.w3.org/WAI/ARIA/apg/patterns/combobox/) and seeing to what extent this library follows that pattern, I noticed that the form input is using `aria-owns`, which appears to be a ARIA 1.0 recommendation. At the bottom of the page, there is a note:

> In ARIA 1.0, the combobox referenced its popup with [aria-owns](https://w3c.github.io/aria/#aria-owns) instead of [aria-controls](https://w3c.github.io/aria/#aria-controls). While user agents might support comboboxes with [aria-owns](https://w3c.github.io/aria/#aria-owns) for backwards compatibility with legacy content, it is strongly recommended that authors use [aria-controls](https://w3c.github.io/aria/#aria-controls).

Is there any possibility that you can update to use `aria-controls` instead of `aria-owns`, or a reason why one would not want to use aria-controls?

**Comment by eugeniosegala** [comment]
Echoing @jeremyZX, I have seen this being flagged as a critical accessibility issue by AXE:

```
Fix any of the following: Required ARIA attribute not present: aria-controls
```

Any chances we could update this? Happy to create a PR but wanted to discuss here before.

**Comment by 36degrees** [comment]
We've [previously said this might be part of an intentional 'regression' to prefer the ARIA 1.0 pattern](https://github.com/alphagov/accessible-autocomplete/pull/386#issuecomment-550367646) due to better support from assistive technologies.

That was 4 years ago, so you'd hope that support for the 1.1 pattern had improved regardless, but we need to understand the nuance of this change and ensure it's thoroughly tested.

**Comment by igneosaur** [comment]
This has also been flagged as part of our accessibility autit for a project in DWP. Would it be resonable to add both attributes? Then we'd be backward compatible and the component would no longer get flagged.
